OBJ := postfixEval.o expressionEvaluation.o reverseString.o infixToprefix.o infixTopostfix.o isOperator.o checkPrecedence.o peek.o peep.o pop.o push.o main.o

main.exe: $(OBJ)
	gcc -o $@ $^

$(OBJ):

clean:
	rm *.o *.exe
	
